input:touchscreen:NVT_Touch_ASUS: fix sysfs store callback to use const char *buf
Newer kernels require sysfs store callbacks to take a const
input buffer. Fix incompatible function pointer warnings.

error:
../drivers/input/touchscreen/NVT_Touch_ASUS/nt36xxx.c:268:52: error: incompatible function pointer types initializing 'ssize_t (*)(struct kobject *, struct kobj_attribute *, const char *, size_t)' (aka 'long (*)(struct kobject *, struct kobj_attribute *, const char *, unsigned long)') with an expression of type 'ssize_t (struct kobject *, struct kobj_attribute *, char *, size_t)' (aka 'long (struct kobject *, struct kobj_attribute *, char *, unsigned long)') [-Wincompatible-function-pointer-types] 268 | gesture_store); | ^~~~~~~~~~~~~ ../include/linux/sysfs.h:105:11: note: expanded from macro '__ATTR' 105 | .store = _store, \ | ^~~~~~ ../drivers/input/touchscreen/NVT_Touch_ASUS/nt36xxx.c:290:52: error: incompatible function pointer types initializing 'ssize_t (*)(struct kobject *, struct kobj_attribute *, const char *, size_t)' (aka 'long (*)(struct kobject *, struct kobj_attribute *, const char *, unsigned long)') with an expression of type 'ssize_t (struct kobject *, struct kobj_attribute *, char *, size_t)' (aka 'long (struct kobject *, struct kobj_attribute *, char *, unsigned long)') [-Wincompatible-function-pointer-types] 290 | screengesture_store); | ^~~~~~~~~~~~~~~~~~~ ../include/linux/sysfs.h:105:11: note: expanded from macro '__ATTR' 105 | .store = _store, \ | ^~~~~~ 2 errors generated.

Signed-off-by: muralivijay <muralidharan9845@gmail.com>